// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package datastore

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID   int64
	Name string
	Bio  pgtype.Text
}

type DualBattle struct {
	ID            int32
	UserID        int32
	RedScores     []float32
	BlueScores    []float32
	RedPenalties  []float32
	BluePenalties []float32
	CreatedAt     pgtype.Timestamptz
	IsCompleted   pgtype.Bool
}

type SingleBattle struct {
	ID          int32
	UserID      int32
	Scores      []float32
	Penalties   []float32
	CreatedAt   pgtype.Timestamptz
	IsCompleted pgtype.Bool
}

type User struct {
	ID           int32
	Username     string
	Email        string
	PasswordHash string
	FirstName    pgtype.Text
	LastName     pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	IsActive     pgtype.Bool
}
